PL/Controllers/EquipoController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json.Linq;
using PL.Models;

namespace PL.Controllers
{
    public class EquipoController : Controller
    {
        public IActionResult GetAll()
        {

            Models.Equipo equipo = new Models.Equipo(); 

            using(var client  = new HttpClient()) 
            {
                client.BaseAddress = new Uri("http://192.168.0.123/api/");
                var responseTask = client.GetAsync("equipo/getall");
                responseTask.Wait();    

                var resultServicio = responseTask.Result;

                if(resultServicio.IsSuccessStatusCode) 
                {
                    var readTask = resultServicio.Content.ReadAsAsync<List<Equipo>>();
                    readTask.Wait();

                    equipo.Equipos = new List<Object>();

                    foreach(var resultEquipo in readTask.Result) 
                    {
                        Equipo aux = new Equipo();  

                        aux.IdEquipo = resultEquipo.IdEquipo;   

                        aux.Nombre = resultEquipo.Nombre;   

                        aux.Pais = new Pais();

                        aux.Pais.IdPais = resultEquipo.Pais.IdPais;

                        aux.Pais.Nombre = resultEquipo.Pais.Nombre;

                        equipo.Equipos.Add(aux);    
                    
                    }

                }

            }


            return View(equipo);
        }


        public IActionResult Form(int? IdEquipo)
        {
            Models.Equipo equipo = new Models.Equipo();
            if(IdEquipo != 0)
            {
                using(var client = new HttpClient()) 
                {
                    client.BaseAddress = new Uri("http://192.168.0.123/api/");

                    var responseTask = client.GetAsync("equipo/getbyid/" + IdEquipo);
                    responseTask.Wait();

                    var resultServicio = responseTask.Result;
                    if (resultServicio.IsSuccessStatusCode)
                    {
                        var readTask = resultServicio.Content.ReadAsStringAsync();
                        dynamic resultJson = JArray.Parse(readTask.Result);
                        readTask.Wait(); 
                        
                      
                    }

                
                
                }
            }



            return View();
        }





    }
}

PL/Controllers/EstadioController.cs
using Microsoft.AspNetCore.Mvc;
using PL.Models;

namespace PL.Controllers
{
    public class EstadioController : Controller
    {
        public IActionResult GetAll()
        {
            Models.Estadio estadio = new Models.Estadio();

            using(var client = new HttpClient()) 
            {
                client.BaseAddress = new Uri("http://192.168.0.123/api/");
                var resposeTask = client.GetAsync("estadio");
                resposeTask.Wait(); 

                var resultServicio = resposeTask.Result;

                if(resultServicio.IsSuccessStatusCode) 
                {
                    var readTask = resultServicio.Content.ReadAsAsync<List<Estadio>>();
                    readTask.Wait();

                    estadio.Estadios = new List<Object>();

                    foreach(var resultEstadio in readTask.Result) 
                    {
                        Estadio aux = new Estadio();    

                        aux.IdEstadio = resultEstadio.IdEstadio;    

                        aux.Nombre = resultEstadio.Nombre;

                        aux.Foto = resultEstadio.Foto;  

                        aux.Pais = new Pais();

                        aux.Pais.IdPais = resultEstadio.Pais.IdPais;

                        aux.Pais.Nombre = resultEstadio.Pais.Nombre;

                        estadio.Estadios.Add(aux);  
                    
                    
                    }
                
                
                }
            

            
            }

            return View(estadio);
        }

    }
}

PL/Controllers/InicioController.cs
using Microsoft.AspNetCore.Mvc;

namespace PL.Controllers
{
    public class InicioController : Controller
    {
        public IActionResult Inicio()
        {
            return View();
        }
    }
}

PL/Controllers/LigaController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json.Linq;
using PL.Models;

namespace PL.Controllers
{
    public class LigaController : Controller
    {
        public IActionResult GetAll()
        {
            Models.Liga liga = new Models.Liga();   

            using(var client = new HttpClient())
            {
                client.BaseAddress = new Uri("http://192.168.0.123/api/");
                var responseTask = client.GetAsync("liga");
                responseTask.Wait();    

                var resultServicio = responseTask.Result;

                if (resultServicio.IsSuccessStatusCode)
                {
                    var readTask = resultServicio.Content.ReadAsAsync<List<Liga>>();
                    readTask.Wait();

                    liga.Ligas = new List<Object>();

                    foreach(var resultLiga in readTask.Result) 
                    {
                        Models.Liga aux = new Models.Liga();

                        aux.IdLiga = resultLiga.IdLiga;

                        aux.Nombre = resultLiga.Nombre; 

                        aux.Logo = resultLiga.Logo;

                        aux.Pais = new Models.Pais();

                        aux.Pais.IdPais = resultLiga.Pais.IdPais;

                        aux.Pais.Nombre = resultLiga.Pais.Nombre;

                        liga.Ligas.Add(aux);
                    
                    
                    }

                }
            }

            return View(liga);
        }


        [HttpGet]
        public IActionResult Form(int? IdLiga)
        {
            Models.Liga liga = new Models.Liga();
            liga.Pais = new Models.Pais();
            if(IdLiga != null)
            {
                using(var client = new HttpClient()) 
                {
                    client.BaseAddress = new Uri("http://192.168.0.123/api/");
                    var responseTask = client.GetAsync("liga/getbyid/" + IdLiga);
                    responseTask.Wait();    

                    var resultServicio = responseTask.Result;   

                    if(resultServicio.IsSuccessStatusCode) 
                    {
                        var readTask = resultServicio.Content.ReadAsStringAsync();
                        dynamic resultJson = JArray.Parse(readTask.Result);
                        readTask.Wait();

                        liga.IdLiga = resultJson[0]["idLiga"];
                        liga.Nombre = resultJson[0]["nombre"];
                        liga.Logo = resultJson[0]["logo"];
                        liga.Pais.IdPais = resultJson[0]["pais"]["idPais"];
                    }

                }

            }
            else
            {
                return View();
            }

            return View(liga);
        }


        [HttpPost]
        public IActionResult Form(Models.Liga liga)
        {
            if(liga.IdLiga == 0)
            {
                using(var client = new HttpClient()) 
                {
                    client.BaseAddress = new Uri("http://192.168.0.123/api/");
                    var postTask = client.PostAsJsonAsync("liga", liga);
                    postTask.Wait();

                    var resultServicio = postTask.Result;

                    if (resultServicio.IsSuccessStatusCode)
                    {
                        return RedirectToAction("GetAll");
                    }
                    else
                    {
                        return View(liga);
                    }
                
                }


            }
            else
            {

                
                using(var client = new HttpClient())
                {
                    int IdLiga = liga.IdLiga;
                    client.BaseAddress = new Uri("http://192.168.0.123/api/");
                    var putTask = client.PutAsJsonAsync("liga/update/" + IdLiga, liga);
                    putTask.Wait(); 

                    var resultServicio = putTask.Result;

                    if (resultServicio.IsSuccessStatusCode)
                    {
                        return RedirectToAction("GetAll");
                    }
                    else
                    {
                        return View(liga);  
                    }

                }
            }
            

        }

        public IActionResult Delete(int IdLiga)
        {
            using(var client = new HttpClient()) 
            {
                client.BaseAddress = new Uri("http://192.168.0.123/api/");
                var deletedTask = client.DeleteAsync("liga/delete/" + IdLiga);
                deletedTask.Wait();

                var resultServicio = deletedTask.Result;

                if (resultServicio.IsSuccessStatusCode)
                {
                    return RedirectToAction("GetAll");
                }
                else
                {
                    return RedirectToAction("GetAll");
                }

            }

        }


      

    }
}

PL/Views/Inicio/Inicio.cshtml
@{
    ViewData["Title"] = "Inicio";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1 class="text-center">Bienvenido</h1>
<br />

<div id="carouselExampleInterval" class="carousel slide" data-bs-ride="carousel">

    <div class="carousel-inner">
        <div class="carousel-item active" data-bs-interval="10000">
            <img src="https://www.nebrija.com/medios/nebrijaglobalcampus/wp-content/uploads/sites/31/2020/06/shutterstock_1066064930b-scaled.jpg" class="d-block w-100" alt="Cargando">
        </div>
        <div class="carousel-item" data-bs-interval="2000">
            <img src="https://www.nexcare.com.mx/wps/wcm/connect/10c4f9c8-dec9-45b6-bc76-a71c6fc00c91/1/Actividades_deportivas_1200x400.jpg?MOD=AJPERES" class="d-block w-100" alt="Cargando">
        </div>
        <div class="carousel-item">
            <img src="https://conecta.tec.mx/sites/default/files/styles/header_full/public/2021-12/foto-portada-deportes-en-el-2022.jpg?itok=cj5bToMV" class="d-block w-100" alt="Cargando">
        </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleInterval" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleInterval" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
    </button>

</div>

<br />
<br />

<div class="row">

    <div class="col-md-6">
        <div class="card" style="width: 18rem;">
            <img src="https://cdn-ehflo.nitrocdn.com/UOvVgTOyzUrmhYwfcXfLEQcHpnXvZZvZ/assets/static/optimized/rev-8814dc6/blog/wp-content/uploads/2022/02/AdobeStock_315861649-1.jpeg" class="card-img-top" alt="Cargando">
            <div class="card-body">
                <h5 class="card-title">Estadios</h5>
                <a href="@Url.Action("GetAll","Estadio")" class="btn btn-primary">Go</a>
            </div>
        </div>


    </div>


    <div class="col-md-6">

        <div class="card" style="width: 18rem;">
            <img src="https://cadenaser.com/resizer/JN10rfnkYyf5z-9oOSoToW68hRE=/736x552/filters:format(jpg):quality(70)/cloudfront-eu-central-1.images.arcpublishing.com/prisaradio/XNOHFG2XS5AN7CNMSFVMIZSWQQ.jpg" class="card-img-top" alt="Cargando">
            <div class="card-body">
                <h5 class="card-title">Jugadores</h5>
                <a href="@Url.Action("GetAll, Jugador")" class="btn btn-primary">Go</a>
            </div>
        </div>
    </div>

<div>



<br />

<div class="row">

    <div class="col-md-6">

                <div class="card" style="width: 18rem;">
                    <img src="https://e00-mx-marca.uecdn.es/mx/assets/multimedia/imagenes/2023/02/14/16764003869338.jpg" class="card-img-top" alt="Cargando">
                    <div class="card-body">
                        <h5 class="card-title">Equipos</h5>
                        <a href="@Url.Action("GetAll", "Equipo")" class="btn btn-primary">Go</a>
                    </div>
                </div>
    </div>


<br />


<div class="col-md-6">

                <div class="card" style="width: 18rem;">
                    <img src="https://cdn2.mediotiempo.com/uploads/media/2022/06/22/cuando-inician-las-ligas-top.jpg" class="card-img-top" alt="...">
                    <div class="card-body">
                        <h5 class="card-title">Ligas</h5>
                        <a href="@Url.Action("GetAll", "Liga")" class="btn btn-primary">Go</a>
                    </div>
                </div>



</div>



</div>